### ISSUE TITLE
Further custom QuTiP functions 

### ISSUE THREAD

**Issue by araza6** [qgrad/qgrad#21]
Since JAX wrapper is not so straight-forward, @quantshah has suggested writing our own light-weight JAX-compatible custom functions. We have started off with basic fidelity function already. I am opening this issue to discuss what other functions we may be needing. I think we can probably write our JAX compatible versions of matrix exponentials, to begin with, followed by the displace operator?

In the meantime, it seems that [Pytorch](https://pytorch.org/docs/stable/notes/extending.html) shall be easier to interface with, rather than JAX. So, I shall be exploring that in the meanwhile.

**Comment by araza6** [comment]
Starting QuTiP functions we would need for most hamiltonians to get started:
1. `sigmaz`, `sigmax`, `sigmay`
2. creation and annihilation
3. `displace`
4. `squeeze`

**Comment by quantshah** [comment]
Fidelity between two density matrices

```
@tf.function()
def fidelity(A, B):
    """
    Calculated the fidelity between batches of tensors A and B
    """
    sqrtmA = tf.matrix_square_root(A)
    temp = tf.matmul(sqrtmA, B)
    temp2 = tf.matmul(temp, sqrtmA)
    fidel = tf.linalg.trace(tf.linalg.sqrtm(temp2))**2
    return tf.math.real(fidel)
```

And expect function

**Comment by araza6** [comment]
@quantshah, for `displace` function, are we going to make our own class-based API here, or move on with the functional paradigm that Jake suggested on the core repo?

**Comment by araza6** [comment]
Further functions to add following the discussion with @quantshah 
1. `coherent` -- Returns a  coherent state (ket)
2. `dag(state)` -- Dagger operation on a state
3. `basis(n, idx)` -- to return a ket with 1 at idx
4. `fock(N, n)` -- bosonic fock state

**Comment by araza6** [comment]
Closing this on https://github.com/qgrad/qgrad/pull/22
