### ISSUE TITLE
qgrad.Qobj class

### ISSUE THREAD

**Issue by araza6** [qgrad/qgrad#23]
It seems that we can't get away with the light-weight _functional_ wrapper for long. A `qgrad.Qobj` class seems necessary. What do you guys think?

**Comment by araza6** [comment]
For instance in `expectation` function that I am working on, I could just use `.is_oper` attribute to decide whether to take trace or not

**Comment by araza6** [comment]
But we need to be cautious not to pass call objects as parameters to functions that we need to take a derivative of of

**Comment by nathanshammah** [comment]
It looks a fair working route to me.

**Comment by araza6** [comment]
@nathanshammah Now that I look back, I think we will run into the same problem with `qgrad` class as we did with `Qobj` in QutTiP. I guess we better stick with the functional approach (at least for the moment) as there is no urgent need yet.
