### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nathanshammah** [qgrad/qgrad#5]
A license needs to be added to the code. I suggest using BSD New v. 3.0 for full compatibility with QuTiP and the NumPy stack. @araza6, Github [will prompt](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) the templates directly once you try to add a file called LICENSE from the web interface. This can still be added as a PR then, instead of merging to master.

**Comment by araza6** [comment]
Closing this issue with PR https://github.com/qgrad/qgrad/pull/7
