### ISSUE TITLE
Bug in coherent function

### ISSUE THREAD

**Issue by araza6** [qgrad/qgrad#51]
coherent function for any Hilbert size, with alpha being zero gives nan array. To reproduce, write `coherent(N, 0)`. Coherent uses `Displace`, so I am assuming the bug is somewhere there

**Comment by nathanshammah** [comment]
Can you please paste a code snippet here? Can you please add the same snippet from qutip?

**Comment by araza6** [comment]
In qgrad, 

```python
from qgrad.qgrad_qutip import coherent
coherent(5, 0)
```
Returns
```
DeviceArray([[nan+nanj],
             [nan+nanj],
             [nan+nanj],
             [nan+nanj],
             [nan+nanj]], dtype=complex64)
```

In QuTiP:

```python
from qutip import coherent
coherent(5, 0)
```

Returns

```
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
1.00.00.00.00.0
```
