### ISSUE TITLE
_fidelity_dm is not jax compatible

### ISSUE THREAD

**Issue by quantshah** [qgrad/qgrad#53]
I was trying to work with density matrices and realised that the fidelity function uses matrix square root from scipy `sqrtm` which is not jax compatible. Jax has not yet implemented `sqrtm` so we cannot work with density matrices yet. This is a problem for us which need to be fixed either by implementing the sqrtm function ourself/finding other ways to compute fidelity between two density matrices.

**Comment by nathanshammah** [comment]
Would pushing feature requests to JAX be an option? That would be a smart way to deal with these sort of shortcomings.

**Comment by quantshah** [comment]
Jax is implementing it now I suppose:
https://github.com/google/jax/issues/2478
