### ISSUE TITLE
PyPI with Twine upload error

### ISSUE THREAD

**Issue by araza6** [qgrad/qgrad#9]
I have been trying uploading the package via Twine, but it gives the following error 
 
> HTTPError: 403 Client Error: Invalid or non-existent authentication information. for URL: https://upload.pypi.org/legacy/

This issue seems to be unresolved as yet on twine's GitHub issues [here](https://github.com/pypa/twine/issues/424). Did you guys face similar issues deploying QuTiP?

**Comment by nathanshammah** [comment]
I recently followed the instructions in [here](https://github.com/nathanshammah/scikit-project/blob/master/6-distribute.md) and everything worked fine. However, at the moment I'd focus on code features, design, and algorithmic development as well as integration with QuTiP. This is low priority.

**Comment by quantshah** [comment]
This can be closed and I can take care of such issues in the future. We have the qgrad project name on PyPi now so let us start coding.

https://pypi.org/project/qgrad/
